spring.application.name=events
# Database connection - REPLACE with your cloud PostgreSQL URL
spring.datasource.url=jdbc:postgresql://localhost:5432/factory_events_db?reWriteBatchedInserts=true

spring.datasource.username=postgres
spring.datasource.password=9293405122@Aa
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP connection pool settings for high performance
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
#logging.level.root=ERROR

# Application runs on port 8080
server.port=8080

# Enable SQL logging during development (optional)
logging.level.org.springframework.jdbc.core=DEBUG